version: '3'

services:  
  db:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./docker_data/mysql:/var/lib/mysql
    env_file:
      - .env
    ports:
      - 3306:3306

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  be:
    container_name: fastapi
    build: .
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
      - redis